version: '3.7'
services:
  master:
    image: redis
    container_name: redis-master
    restart: always
    command: redis-server --port 6379 --requirepass 1234 --masterauth 1234 --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./data/master:/data
    environment:
      - TZ=Asia/Shanghai

  slave1:
    image: redis
    container_name: redis-slave-1
    restart: always
    command: redis-server --slaveof 172.20.80.159 6379 --port 6380  --requirepass 1234 --masterauth 1234  --appendonly yes
    ports:
      - 6380:6380
    volumes:
      - ./data/slave-1:/data
    environment:
      - TZ=Asia/Shanghai

  slave2:
    image: redis
    container_name: redis-slave-2
    restart: always
    command: redis-server --slaveof 172.20.80.159 6379 --port 6381  --requirepass 1234 --masterauth 1234  --appendonly yes
    ports:
      - 6381:6381
    volumes:
      - ./data/slave-2:/data
    environment:
      - TZ=Asia/Shanghai
