version: '3.4'
services:
  master:
    image: redis
    container_name: redis-master
    restart: always
    command: redis-server /etc/redis/redis.conf --appendonly yes
    volumes:
          - ./conf/redis.conf:/etc/redis/redis.conf:rw
          - ./data/redis-master:/data:rw
#    network_mode: "host"
    ports:
      - 6379:6379

  slave1:
    image: redis
    container_name: redis-slave-1
    restart: always
    command: redis-server /etc/redis/redis.conf --slaveof 172.20.80.159 6379 --port 6380 --requirepass 1234 --masterauth 1234
#    network_mode: "host"
    volumes:
         - ./conf/redis.conf:/etc/redis/redis.conf:rw
         - ./data/redis-slave-1:/data:rw
    ports:
      - 6380:6379


  slave2:
    image: redis
    container_name: redis-slave-2
    restart: always
    command: redis-server /etc/redis/redis.conf --slaveof 172.20.80.159 6379 --port 6381 --requirepass 1234 --masterauth 1234
    volumes:
         - ./conf/redis.conf:/etc/redis/redis.conf:rw
         - ./data/redis-slave-2:/data:rw
#    network_mode: "host"
    ports:
      - 6381:6379

