version: '3'
services:
  #====================================================================================================================#
  #================================================== springboot install ==============================================#
  #====================================================================================================================#
  # 1.默认: 放置ROOT目录 8088端口  访问地址：http://112.74.185.172:8080/    ->  修改IP即可
  springboot:
    hostname: springboot
    # only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed
    container_name: springboot
    # 2.解决容器的依赖、启动先后的问题
    # depends_on:
    #   - mysql
    # 3.选择自己镜像构建的方式 -> image: 远程仓库拉取 or build:上下文构建(可对项目代码进行)
    #image: java:8
    build: ./bulid
    # 4.可通过./tomcat/conf/server.xml设置服务端口
    ports:
      - 8088:8080
    # 5.定义IP网络
   # links:
   #   - mysql
   # networks:
   #   staticneta:
   #     ipv4_address: 172.21.1.2
    #    - 80:80
    #    - 443:443
    # 6.挂载目录
    #volumes:
    #  - ./tomcat/webapps:/usr/local/tomcat/webapps
    #  - ./tomcat/logs:/usr/local/tomcat/logs
    #  - ./tomcat/conf:/usr/local/tomcat/conf
    # 7.设置环境变量: 时区与编码
    #   你可以使用数组或字典两种格式
    #   只给定名称的变量会自动获取运行 Compose 主机上对应变量的值，可以用来防止泄露不必要的数据
    environment:
      JAVA_OPTS: -Dfile.encoding=UTF-8
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    # 8.生产环境配置：指定容器退出后的重启策略为始终重启, 对保持服务始终运行十分有效
    restart: always