version: '3'
services:
  #服务名称
  mssql:
    #容器名称
    container_name: mssql
    #镜像名称
    image: mcr.microsoft.com/mssql/server:2017-latest
    #总是重启后启动
    restart: always
    #端口映射
    ports:
      - 1433:1433
    #挂载
    volumes:
      - ./data:/var/opt/mssql
    #环境变量
    environment:
      - ACCEPT_EULA=Y
      #SA用户密码
      - SA_PASSWORD=QWE@qwe123
#启动完成后进入容器创建数据库
#docker exec -it mssql bash
#/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "QWE@qwe123"
#create database sq_173cms
#go
#ALTER DATABASE sq_173cms COLLATE Chinese_PRC_CI_AS
#go
#drop database sq_173cms