version: '3.7'
services:
  sentinel1:
    image: redis
    container_name: redis-sentinel-1
    ports:
      - 26379:26379
    volumes:
      - ./sentinel1.conf:/etc/redis/sentinel.conf
    command: redis-sentinel /etc/redis/sentinel.conf
    restart: always
    environment:
      - TZ=Asia/Shanghai

  sentinel2:
    image: redis
    container_name: redis-sentinel-2
    ports:
      - 26380:26379
    volumes:
      - ./sentinel2.conf:/etc/redis/sentinel.conf
    command: redis-sentinel /etc/redis/sentinel.conf
    restart: always
    environment:
      - TZ=Asia/Shanghai

  sentinel3:
    image: redis
    container_name: redis-sentinel-3
    ports:
      - 26381:26379
    volumes:
      - ./sentinel3.conf:/etc/redis/sentinel.conf
    command: redis-sentinel /etc/redis/sentinel.conf
    restart: always
    environment:
      - TZ=Asia/Shanghai
