version: '3.7'
services:
  sentinel1:
    image: redis
    privileged: true
    container_name: redis-sentinel-1
    ports:
      - 26379:26379
    volumes:
       - ./conf/1:/etc/redis
    command: redis-sentinel /etc/redis/sentinel.conf
    restart: always
    environment:
      - TZ=Asia/Shanghai

  sentinel2:
    image: redis
    privileged: true
    container_name: redis-sentinel-2
    ports:
      - 26380:26379
    volumes:
      - ./conf/2:/etc/redis
    command: redis-sentinel /etc/redis/sentinel.conf
    restart: always
    environment:
      - TZ=Asia/Shanghai

  sentinel3:
    image: redis
    privileged: true
    container_name: redis-sentinel-3
    ports:
      - 26381:26379
    volumes:
      - ./conf/2:/etc/redis
    command: redis-sentinel /etc/redis/sentinel.conf
    restart: always
    environment:
      - TZ=Asia/Shanghai
